import React from "react";
import "./Index.css";
import copyrighticon from "../../Assets/copyrighticon.svg";

function Information() {
  return (
    <div className="Informationon">
      <div className="informationsec1">
        <p>
          <span style={{ fontWeight: "bold" }}>
            SHADOWBOX - BETA STATEMENT - CORPORATE DISCLAIMER A.)
            DOMAIN-GENERAL-CORPORATE DISCLAIMER:
          </span>{" "}
          SELECT STATEMENTS AND REFERENCES DOCUMENTED ON OUR SITES, SOCIAL I?1
          0111 iraNTEDDigaTNI ED=0117017= ?1,1P=g119A IVIICC111A21 1174
          LOPFLFTINOEVYNOUT OITA'S (7.11MT= AN OFFER TO BUY OR SELL ANY:
          CRYPTOCURRENCY SECURITY. PRODUCT. SERVICE. AND/OR INVESTMENT. PLEASE
          SEEK A DULY LICENSED PROFESSIONAL FOR INVESTMENT ADVICE. THE
          INFORMATION PROVIDED HERE OR IN ANY COMMUNICATION CONTAINING A LINK TO
          OUR SITES. IS NOT INTENDED FOR DISTRIBUTION TO. OR USE BY. ANY PERSON
          OR ENTITY IN ANY JURISDICTION OR COUNTRY WHERE SUCH DISTRIBUTION OR
          USE WOULD BE CONTRARY TO LAW OR REGULATION OR WHICH WOULD SUBJECT
          CORNERMAN. INC. AND/OR ITS AFFILIATES INCLUDING THE SHADOWBOX GROUP
          (SBG) AND/OR FORTHCOMING RINGSIDE FOUNDATION (CURRENTLY UNDER
          COMPLETION OF ITS QUALITY POLICY. PRELIMINARY FILINGS. AND DOCUMENT
          REVISION PRIOR TO OFFICIAL LAUNCH PHASES IN (2o22-2o231. ITS TO ANY
          REGISTRATION REQUIREMENT WITHIN SUCH JURISDICTION OR COUNTRY. NEITHER
          THE INFORMATION. NOR ANY OPINION CONTAINED IN THIS SITE (AND/OR
          AFFILIATE DOMAINS) CONSTITUTES A SOLICITATION OR OFFER BY CORNERMAN.
          INC.. AND/OR ITS AFFILIATES INCLUDING THE SHADOWBOX GROUP (SBG). TO
          BUY OR SELL ANY: CRYPTOCURRENCIES. SECURITIES. FUTURES. OPTIONS.
          AND/OR OTHER FINANCIAL INSTRUMENTS. AND/OR PROVIDE ANY INVESTMENT
          ADVICE OR SERVICE.{" "}
          <span style={{ fontWeight: "bold" }}>
            B.) CRYPTO-ASSETS-CORPORATE DISCLAIMER:
          </span>{" "}
          CRYPTO ASSETS ARE INTANGIBLE DIGITAL ASSETS. THEY EXIST ONLY BY VIRTUE
          OF THE OWNERSHIP RECORD MAINTAINED IN THE ETHEREUM NETWORK. ANY
          TRANSFER OF TITLE THAT MIGHT OCCUR IN ANY UNIQUE DIGITAL ASSET OCCURS
          ON THE DECENTRALIZED LEDGER WITHIN THE ETHEREUM PLATFORM. WE DO NOT
          GUARANTEE THAT SHADOWBOX OR ANY SHADOWBOX PARTY CAN EFFECT THE
          TRANSFER OF TITLE OR RIGHT IN ANY CRYPTO ASSETS. THIS SERVICE ALSO
          ALLOWS YOU TO SELL AND PURCHASE CRYPTO ASSETS (AS DEFINED BELOW) VIA
          AUCTION CAUCTION, DETAILED RULES REGARDING THE AUCTION PROCESS ARE
          AVAILABLE ON THIS PAGE, AUCTION RULES. YOU MAY ONLY PARTICIPATE IN THE
          AUCTION BY LINKING YOUR DIGITAL WALLETS ON SUPPORTED BRIDGE EXTENSIONS
          SUCH AS METAMASK (HTTPS:// METAMASKI0/). METAMASK IS AN ELECTRONIC
          WALLET. WHICH ALLOWS YOU TO PURCHASE. STORE, AND ENGAGE IN
          TRANSACTIONS USING ETHEREUM CRYPTOCURRENCY. BEFORE PUTTING UP YOUR
          UNIQUE DIGITAL ASSET FOR AUCTION OR PUTTING IN AN OFFER TO PURCHASE A
          UNIQUE DIGITAL ASSET FROM ANOTHER USER. WE WILL ASK YOU TO DOWNLOAD A
          SUPPORTED ELECTRONIC WALLET EXTENSION, AND CONNECT AND UNLOCK YOUR
          DIGITAL WALLETS WITH THAT EXTENSION. ONCE YOU SUBMIT AN ORDER TO SE.
          OR PURCHASE A UNIQUE DIGITAL ASSET, YOUR ORDER IS PASSED ON TO THE
          APPLICABLE EnENSION, WHICH COMPLETES THE TRANSACTION ON YOUR BEHALF.
          'CRYPT° ASSETS' REFERS TO UNIQUE NON-FUNGIBLE TOKENS. IMPLEMENTED ON
          THE ETHEREUM BLOCKCHAIN (THE -ETHEREUM PLATFORM') USING SMART
          CONTRACTS. INCLUDING WITHOUT LIMITATION ETHMOJI. CRYPTOKITTIES.
          CRYPTOCELEBRITIES, AND CRYPTOPUNKS. SHADOWBOX IS NOT RESPONSIBLE FOR
          SUSTAINED CASUALTIES DUE TO VULNERABILITY OR ANY KIND OF FAILURE.
          ABNORMAL BEHAVIOR OF SOFTWARE (Ea. WALLET. SMART CONTRACT).
          BLOCKCHAINS OR ANY OTHER FEATURES OF THE CRYPTO ASSETS. SHADOWBOX IS
          NOT RESPONSIBLE FOR CASUALTIES DUE TO LATE REPORT BY DEVELOPERS OR
          REPRESENTATIVES (OR NO REPORT AT ALU OF ANY ISSUES WITH THE BLOCKCHAIN
          SUPPORTING CRYPTO ASSETS INCLUDING FORKS. TECHNICAL NODE ISSUES OR ANY
          OTHER ISSUES HAVING FUND LOSSES AS A RESULT. THANK YOU
        </p>
      </div>
      <div className="informationsec2">
        <img src={copyrighticon} />
        <p>CORNERMAN, INC. - THE SHADOWBOX GROUP (SBG) </p>
      </div>
    </div>
  );
}
export default Information;
